apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: getports
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: testcron
          containers:
          - name: getports
            image: bitnami/kubectl:latest
            command: ["kubectl", "get" ,"svc", "-o=jsonpath= \'{range .items[*]} {@.metadata.name}{\": \"}{@.spec.ports[*].port}{\"\\n\"}{end}\'"]
          restartPolicy: OnFailure
