apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cron-role-bind
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cron-cluster-role
subjects:
- kind: ServiceAccount
  name: testcron
  namespace: default
